In [1]:
import numpy as np
import pandas as pd

In [70]:
df=pd.read_csv('titanic.csv')
df.head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

1. Display:
   - first 10 rows
   - last 10 rows
   - dataset shape
   - column names

In [8]:
#first 10 rows
df.head(10)

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN
5         0       3    male   NaN      0      0   8.4583        Q  NaN
6         0       1    male  54.0      0      0  51.8625        S    E
7         0       3    male   2.0      3      1  21.0750        S  NaN
8         1       3  female  27.0      0      2  11.1333        S  NaN
9         1       2  female  14.0      1      0  30.0708        C  NaN

In [5]:
df.tail(10)

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
881         0       3    male  33.0      0      0   7.8958        S  NaN
882         0       3  female  22.0      0      0  10.5167        S  NaN
883         0       2    male  28.0      0      0  10.5000        S  NaN
884         0       3    male  25.0      0      0   7.0500        S  NaN
885         0       3  female  39.0      0      5  29.1250        Q  NaN
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

In [9]:
# dataset shape
df.shape

(891, 9)

In [7]:
df.columns

Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

2. find
   - total number of passengers
   - number of male passengers
   - number of female passengers

In [35]:
# total number of passengers
df.shape[0]

891

In [13]:
df['gender'].value_counts()

gender
male      577
female    314
Name: count, dtype: int64

3. Display
   - data tpes of all columns
   - number of missing values in each column

In [23]:
df.dtypes

survived      int64
pclass        int64
gender       object
age         float64
sibsp         int64
parch         int64
fare        float64
embarked     object
deck         object
dtype: object

In [24]:
df.isnull().sum()

survived      0
pclass        0
gender        0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

4. find
   - minimum age
   - maximum age
   - average age
   - median age

In [26]:
df['age'].min()

0.42

In [27]:
df['age'].max()

80.0

In [30]:
print(df['age'].mean())

29.69911764705882

In [31]:
print(df['age'].median())

28.0

5. Display all passengers:
   - whose age is greater than 60

In [36]:
df[ df['age'] >60 ].head()  #whose age is greater than 60

     survived  pclass gender   age  sibsp  parch     fare embarked deck
33          0       2   male  66.0      0      0  10.5000        S  NaN
54          0       1   male  65.0      0      1  61.9792        C    B
96          0       1   male  71.0      0      0  34.6542        C    A
116         0       3   male  70.5      0      0   7.7500        Q  NaN
170         0       1   male  61.0      0      0  33.5000        S    B

6. Display all female passengers
   - travelling in first class

In [38]:
df[ (df['gender']=='female') & (df['pclass'] ==1) ]

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
1           1       1  female  38.0      1      0   71.2833        C    C
3           1       1  female  35.0      1      0   53.1000        S    C
11          1       1  female  58.0      0      0   26.5500        S    C
31          1       1  female   NaN      1      0  146.5208        C    B
52          1       1  female  49.0      1      0   76.7292        C    D
..        ...     ...     ...   ...    ...    ...       ...      ...  ...
856         1       1  female  45.0      1      1  164.8667        S  NaN
862         1       1  female  48.0      0      0   25.9292        S    D
871         1       1  female  47.0      1      1   52.5542        S    D
879         1       1  female  56.0      0      1   83.1583        C    C
887         1       1  female  19.0      0      0   30.0000        S    B

[94 rows x 9 columns]

7. Display passengers:
   - who survived
   - and whose fare was greater than 50

In [41]:
df[ (df['survived'] == 1) & (df['fare'] > 50) ]

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
1           1       1  female  38.0      1      0   71.2833        C    C
3           1       1  female  35.0      1      0   53.1000        S    C
31          1       1  female   NaN      1      0  146.5208        C    B
52          1       1  female  49.0      1      0   76.7292        C    D
61          1       1  female  38.0      0      0   80.0000      NaN    B
..        ...     ...     ...   ...    ...    ...       ...      ...  ...
838         1       3    male  32.0      0      0   56.4958        S  NaN
849         1       1  female   NaN      1      0   89.1042        C    C
856         1       1  female  45.0      1      1  164.8667        S  NaN
871         1       1  female  47.0      1      1   52.5542        S    D
879         1       1  female  56.0      0      1   83.1583        C    C

[109 rows x 9 columns]

8. Display:
   - passenger name, age, fare
   - for passengers embarked from 'C'

In [111]:
df_8=df[ df['embarked']=='C' ]
df_8.loc[[],['age','fare']]

Empty DataFrame
Columns: [age, fare]
Index: []

9. display passengers
    - whose age is between 20 and 30
    - and who did not survive

In [54]:
df[ ( df['age'].between(20,30) ) & (df['survived']==0) ]

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
12          0       3    male  20.0      0      0   8.0500        S  NaN
34          0       1    male  28.0      1      0  82.1708        C  NaN
37          0       3    male  21.0      0      0   8.0500        S  NaN
41          0       2  female  27.0      1      0  21.0000        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
876         0       3    male  20.0      0      0   9.8458        S  NaN
882         0       3  female  22.0      0      0  10.5167        S  NaN
883         0       2    male  28.0      0      0  10.5000        S  NaN
884         0       3    male  25.0      0      0   7.0500        S  NaN
886         0       2    male  27.0      0      0  13.0000        S  NaN

[158 rows x 9 columns]

10. top 5 passengers with highest fare

In [55]:
df.nlargest(5,'fare')

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
258         1       1  female  35.0      0      0  512.3292        C  NaN
679         1       1    male  36.0      0      1  512.3292        C    B
737         1       1    male  35.0      0      0  512.3292        C    B
27          0       1    male  19.0      3      2  263.0000        S    C
88          1       1  female  23.0      3      2  263.0000        S    C

In [58]:
df.sort_values(by='fare',ascending=False).head(5)

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
258         1       1  female  35.0      0      0  512.3292        C  NaN
737         1       1    male  35.0      0      0  512.3292        C    B
679         1       1    male  36.0      0      1  512.3292        C    B
88          1       1  female  23.0      3      2  263.0000        S    C
27          0       1    male  19.0      3      2  263.0000        S    C

11. Display
    - youngest 5 passengers

In [56]:
df.nsmallest(5,'age')

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
803         1       3    male  0.42      0      1   8.5167        C  NaN
755         1       2    male  0.67      1      1  14.5000        S  NaN
469         1       3  female  0.75      2      1  19.2583        C  NaN
644         1       3  female  0.75      2      1  19.2583        C  NaN
78          1       2    male  0.83      0      2  29.0000        S  NaN

In [57]:
youngest_5 = df.sort_values(by='age').head()
youngest_5

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
803         1       3    male  0.42      0      1   8.5167        C  NaN
755         1       2    male  0.67      1      1  14.5000        S  NaN
644         1       3  female  0.75      2      1  19.2583        C  NaN
469         1       3  female  0.75      2      1  19.2583        C  NaN
78          1       2    male  0.83      0      2  29.0000        S  NaN

12. find:
    - average fare for each passenger class(use groupby)

In [73]:
df.groupby('pclass')['fare'].mean()

pclass
1    84.154687
2    20.662183
3    13.675550
Name: fare, dtype: float64

13. find
    - survival count for each gender

In [75]:
df[['gender','survived']].value_counts()

gender  survived
male    0           468
female  1           233
male    1           109
female  0            81
Name: count, dtype: int64

14. find
    - average age of passengers who survived
    - average age of passengers who did not survived

In [77]:
print(df[df['survived']==1]['age'].mean())

28.343689655172415

In [78]:
print(df[df['survived']==0]['age'].mean())

30.62617924528302

15. convert age column into a numpy array and find
    - mean, std dev. , variance (ignore missing values)

In [79]:
arr=np.array(df[['age'])

In [87]:
print(np.nanmean(arr))

29.69911764705882

In [88]:
print(np.nanstd(arr))

14.516321150817316

In [89]:
print(np.nanvar(arr))

210.72357975366614

16. Using numpy create a new column called :
    - fare_with_tax
    - increased fare by 18%

In [92]:
fare_with_tax = np.array(df['fare']) + np.array(df['fare'])*0.18
fare_with_tax

array([  8.555   ,  84.114294,   9.3515  ,  62.658   ,   9.499   ,
         9.980794,  61.19775 ,  24.8685  ,  13.137294,  35.483544,
        19.706   ,  31.329   ,   9.499   ,  36.9045  ,   9.267956,
        18.88    ,  34.3675  ,  15.34    ,  21.24    ,   8.5255  ,
        30.68    ,  15.34    ,   9.474456,  41.89    ,  24.8685  ,
        37.03725 ,   8.5255  , 310.34    ,   9.297456,   9.317044,
        32.710544, 172.894544,   9.145   ,  12.39    ,  96.961544,
        61.36    ,   8.530456,   9.499   ,  21.24    ,  13.265206,
        11.1805  ,  24.78    ,   9.317044,  49.063456,   9.297456,
         9.499   ,  18.29    ,   9.145   ,  25.581456,  21.004   ,
        46.83125 ,   9.204   ,  90.540456,  30.68    ,  73.135456,
        41.89    ,  12.39    ,   8.530456,  32.745   ,  55.342   ,
         8.530456,  94.4     ,  98.5005  ,  32.922   ,  32.710544,
        17.990044,  12.39    ,   9.626794,   9.3515  ,  10.22175 ,
        12.39    ,  55.342   ,  86.73    ,  17.055956,  66.665044,
         9.027   ,   9.317044,   9.499   ,  34.22    ,  14.7205  ,
        10.62    ,  11.21    ,   9.18925 ,  55.578   ,  12.39    ,
        18.703   ,  40.5625  ,   9.499   , 310.34    ,   9.499   ,
         9.499   ,   9.267956,  72.1865  ,  24.2785  ,   8.555   ,
         9.499   ,  40.891956,  74.762794,  27.14    ,  30.68    ,
         9.317044,   9.317044,  91.19925 ,  10.211956,   9.3515  ,
         9.317044,   9.027   ,   9.1745  ,   9.317044,  28.497   ,
        61.36    ,  17.055956,   9.499   ,  11.5935  ,  17.060794,
         9.3515  ,   9.145   ,  24.78    , 292.074544,  36.9045  ,
        86.73    ,   9.499   ,  35.483544,  15.34    ,  91.19925 ,
        13.265206,   9.145   ,   8.427206,  26.382794,   8.2305  ,
         9.317044,   8.319   ,  17.11    ,  30.68    ,  15.34    ,
        17.754044,  31.014294,  62.658   ,  10.875706,  93.456   ,
        17.990044,   9.145   ,  18.703   ,   7.965   ,  13.57    ,
        43.365   ,   9.199044,  40.5625  ,  30.68    ,  15.34    ,
        14.7795  ,  78.588   ,   9.499   ,  17.11    ,   8.62875 ,
        72.427456,   9.125294,   9.499   ,  10.22175 ,  82.069   ,
        18.998   ,  18.585   ,   9.1745  ,  10.22175 ,  46.83125 ,
        24.2195  ,  64.9     ,  32.922   ,  30.5915  ,  66.665044,
        39.53    ,  34.3675  ,  13.137294,   9.3515  ,  36.221044,
         9.267956,  30.050706,  33.88075 ,  15.34    ,   0.      ,
        82.069   ,  17.759   ,  37.03725 ,  46.02    ,  25.9895  ,
        59.      ,  18.29    ,  31.329   ,  18.29    ,   9.317044,
        15.34    ,  15.34    ,   9.267956,  30.68    ,  32.710544,
       172.894544,   9.145   ,   9.916956,   9.145   ,  15.34    ,
        11.21    ,  82.069   ,   7.665044,   8.5255  ,   9.499   ,
        12.34575 ,  18.703   ,  22.16925 ,   9.145   ,  36.58    ,
         8.319   ,  24.78    ,   8.555   ,  15.34    ,   9.145   ,
       133.6645  ,   9.3515  ,  31.86    ,  90.024206,  12.39    ,
         9.499   ,  15.34    ,   9.499   ,   9.317044, 106.2     ,
        11.033   ,  12.39    ,   8.555   ,  15.34    ,  30.050706,
        98.5005  ,   9.1745  ,  15.93    ,  37.03725 ,  12.39    ,
         8.909   ,  30.68    ,  30.975   ,  12.39    ,  14.4845  ,
        17.055956,  18.29    ,  12.39    ,   8.4075  ,   8.5255  ,
       106.2     ,   9.1745  ,  17.11    ,  62.013956,  30.68    ,
         8.555   ,  12.34575 ,  31.329   ,  18.998   ,  23.85075 ,
        17.990044,  93.456   , 102.07    , 604.548456,  30.68    ,
         9.145   ,  37.03725 ,  93.987   ,   0.      ,   9.145   ,
        12.39    ,  46.83125 ,   9.1745  , 181.08575 , 160.047294,
        36.58    ,   0.      ,  23.01    ,  35.046   ,   9.145   ,
        91.990794,   9.145   ,   0.      ,  34.3675  ,  23.895   ,
         9.145   ,   9.267956,  11.21    ,   9.499   ,  30.68    ,
        10.22175 ,  11.21    ,   9.317044,  15.34    ,   9.145   ,
        93.043   , 107.473456,  15.1925  ,  10.443   ,   9.317044,
        32.710544,   8.530456, 178.829   ,  35.99    , 292.074544,
         9.145   ,  27.435   ,   0.      ,  14.573   ,   9.499   ,
       178.829   , 130.842294, 128.502   ,  28.32    ,  67.176456,
        98.126794, 309.6025  ,  30.68    ,   9.317044,  30.975   ,
         9.267956,  30.68    ,  16.52    , 194.542706, 158.71    ,
         8.555   ,   9.317044,  14.573   ,  34.22    ,  82.069   ,
       160.047294,   7.36025 ,  15.34    ,  24.2195  ,  68.415456,
        27.435   ,  33.63    , 181.08575 ,  21.24    , 157.707   ,
         9.317044,  78.588   , 158.71    ,   9.499   ,  41.89    ,
        30.68    , 310.34    ,  15.34    ,  15.34    ,  15.34    ,
        15.34    ,  15.34    ,  18.998   ,  18.762   ,  10.22175 ,
        10.8855  ,  41.3     ,   8.530456,  21.004   ,   8.5255  ,
        11.21    ,  64.9     ,  15.34    ,   9.297456,   9.297456,
        32.922   ,  32.710544,  17.055956,   8.319   ,  18.29    ,
         8.555   ,  88.795   ,   8.530456,   9.145   ,  81.774   ,
        65.421206,   7.665044,   9.499   , 160.047294,  24.8685  ,
        96.961544,   8.555   , 249.57    ,   4.73475 ,   9.1745  ,
       268.4795  ,  18.575206,   9.3515  ,  61.36    ,   9.317044,
        86.73    ,  55.342   ,  15.34    ,   9.120456,  14.16    ,
       141.6     ,   9.199044,   9.3515  , 133.6645  ,  19.706   ,
         9.199044,   9.267956,  30.68    ,  12.39    ,  14.927   ,
         9.3515  ,   9.499   ,  11.5935  ,  18.703   ,  10.22175 ,
        24.78    ,   9.145   ,  22.125   ,   9.1745  ,  30.050706,
         9.317044,   8.092794, 106.2     ,   0.      ,   9.3515  ,
         9.499   ,  38.35    ,  15.34    ,  15.34    ,  28.497   ,
         9.317044,   9.125294,   9.2925  ,  16.992   ,  23.85075 ,
         8.555   ,  30.68    ,  30.68    ,   9.145   ,   9.499   ,
        31.329   ,  18.998   ,  30.68    ,   8.4075  ,  65.962   ,
       141.6     ,  40.5625  ,  22.125   , 310.34    ,  12.39    ,
        30.975   ,  11.21    ,   9.1745  ,  15.34    ,   9.57275 ,
        96.592794,  23.01    ,  31.329   ,  22.724794,  35.99    ,
        32.745   ,  23.560706,  32.745   , 105.142956,   9.499   ,
         9.317044,  31.329   ,  61.19775 ,  12.39    ,   9.145   ,
        31.329   ,   9.499   ,  45.43    ,  15.34    ,   9.499   ,
         8.319   ,   0.      ,  31.329   ,   9.1155  ,  22.724794,
         8.555   ,  10.22175 ,  32.745   ,  16.274206,  11.60825 ,
        61.36    ,  24.78    ,   8.314044,   8.874544,  14.49925 ,
        55.342   ,   0.      ,   9.499   ,  11.31325 , 107.473456,
        30.050706, 106.2     ,  35.046   ,   9.499   ,  18.762   ,
        23.560706,   8.555   ,  35.99    ,  58.414956,   9.499   ,
        17.060794,  92.354706,  17.818   , 178.829   ,   9.199044,
        10.22175 ,   9.145   ,   9.002456,  11.31325 , 102.07    ,
       128.502   ,  30.68    ,  31.329   ,  26.5795  ,  66.665044,
         9.145   ,   9.499   ,  31.01925 ,  70.092   ,   8.845044,
        40.144544,  12.39    ,  28.497   ,  30.68    ,   9.317044,
       110.33    ,   9.317044,   8.5255  ,  68.415456,   8.530456,
         9.145   ,  12.39    , 261.699456,   9.3515  ,  13.57    ,
        30.68    ,   8.530456,   8.530456,  26.382794,  10.22175 ,
        30.975   ,  31.329   , 125.5815  ,  17.11    ,  58.41    ,
        83.78    ,  36.9045  ,  36.9045  ,  30.68    , 125.5815  ,
        30.68    ,  30.68    ,  16.35775 ,  24.2195  ,  43.365   ,
       130.842294,  30.68    ,   9.238456,   8.5255  ,   9.1745  ,
        31.329   ,  46.728   , 268.4795  ,  93.987   ,  20.532   ,
         9.145   ,   9.317044,  15.93    ,   9.499   ,   9.499   ,
        28.497   ,   9.317044,  24.8685  ,   8.530456,   9.267956,
        12.39    ,  60.745456,  31.13725 ,   9.145   ,   9.499   ,
        17.11    ,  15.34    ,  65.962   ,  17.060794,   9.3515  ,
        35.4     , 130.842294,  30.68    ,  47.3475  ,  10.28075 ,
        93.987   ,  17.7     ,  93.456   ,   9.499   ,   9.499   ,
         8.4075  ,  92.354706,   8.555   ,   9.145   ,  30.68    ,
        28.497   ,  38.94    ,   0.      ,   8.5255  ,  67.176456,
        31.86    ,   9.317044,  50.032   ,   9.499   ,  31.329   ,
        18.349   ,   9.317044,  35.99    ,  49.063456, 181.08575 ,
        36.9045  ,   8.319   ,  18.29    ,   9.145   ,   9.499   ,
        76.7     ,  16.992   ,  18.998   ,  46.02    ,  12.39    ,
        17.055956,  62.013956,  18.575206,   9.267956,  18.998   ,
        38.138544,  14.573   ,  91.990794,   9.317044,   9.125294,
        35.4     ,   8.323956,  35.99    ,   0.      ,  32.922   ,
        15.34    ,   9.3515  ,  30.975   ,  46.83125 ,  18.998   ,
         9.267956,  81.774   ,  32.922   ,  66.665044,  22.724794,
        90.540456,   9.317044,  41.89    ,   8.909   ,   8.909   ,
         9.317044,  27.14    ,   9.951294,   9.238456,   7.965   ,
        86.73    ,   9.317044,  18.29    ,  15.34    , 133.6645  ,
       157.707   ,   8.5255  ,  30.19325 ,   8.845044,   9.3515  ,
        86.73    ,  15.34    ,   9.1745  ,   9.499   ,  61.36    ,
        46.02    ,  61.36    ,  12.39    ,  15.34    ,   0.      ,
         9.1745  ,   9.499   ,  11.613206,  55.342   , 604.548456,
         9.60225 ,  90.540456,  10.8855  ,  55.342   ,  46.02    ,
        49.063456,  46.83125 ,  12.001544,   9.199044, 249.37825 ,
        67.26    ,  15.831706,  66.665044,   8.5255  ,  31.329   ,
        15.93    ,   9.499   ,   9.125294, 130.842294,   9.027   ,
       268.4795  ,  31.01925 ,  17.055956,   9.135206,   9.267956,
        30.68    ,  15.93    ,  31.01925 , 178.829   ,  17.990044,
        58.414956,  31.329   ,  61.36    ,  11.190294,  15.34    ,
         9.027   , 268.4795  ,  12.39    ,  18.29    ,   9.1745  ,
        38.94    ,   8.323956,  15.34    ,  15.34    ,  62.658   ,
        10.22175 ,  24.78    ,   9.13025 ,  30.68    ,   9.3515  ,
       249.37825 ,  22.16925 ,   0.      ,  15.34    ,  15.34    ,
        18.998   ,  40.5625  , 604.548456,   9.317044,   9.317044,
        35.4     ,  93.043   , 309.6025  ,  18.998   ,   9.3515  ,
        83.78    ,  23.895   ,  15.34    ,  62.658   ,   9.145   ,
        27.14    ,  14.7205  ,  11.21    ,   9.317044,  76.7     ,
        17.11    ,   9.199044,  13.57    ,   9.499   , 102.07    ,
        17.11    ,   8.4075  ,   8.530456, 141.6     ,   9.1745  ,
        91.990794,  46.728   ,   9.145   ,  28.497   ,   9.86775 ,
        11.21    ,   9.267956,  12.39    ,   8.5255  ,  27.14    ,
         9.145   ,   9.145   ,  14.7205  ,   9.13025 , 249.37825 ,
         8.530456,  67.26    ,  35.4     ,  27.671   ,   8.319   ,
         8.555   ,   8.845044,  34.3675  ,  24.2785  ,  93.456   ,
         9.145   ,  30.68    ,  82.069   ,  36.221044,   9.317044,
        15.34    ,  30.596456,  10.246294,   8.530456,  28.497   ,
        15.34    ,  30.975   , 141.6     ,  10.049706,   8.2305  ,
         9.1745  ,   0.      ,   9.1745  ,  15.34    ,  62.658   ,
         9.30725 ,  28.497   ,  12.39    ,  36.9045  ,   9.499   ,
         0.      ,   9.3515  ,  43.664956,   7.611   ,  32.922   ,
       110.33    ,  10.22175 ,   0.      ,  14.7205  ,  46.83125 ,
         8.201   ,  66.665044,  43.664956,   9.145   ,  94.4     ,
        17.055956,  22.125   ,   8.530456,   9.267956,   9.794   ,
        98.126794,  10.22175 ,   9.499   ,  66.665044,  35.046   ,
         9.3515  ,  12.39    ,  36.58    ,   7.59625 ,  10.22175 ,
         8.909   ,  82.069   ,   9.317044,  38.94    , 105.142956,
        36.9045  ,   9.1745  ,  17.990044,  46.492   ,  30.68    ,
        11.033   , 194.542706,  31.329   ,  22.724794,   8.530456,
        16.647794,  13.57    ,  30.596456,  82.069   ,  15.34    ,
        15.34    ,  16.352794,  59.585044,  11.21    ,  13.137294,
         9.317044,  62.013956,   5.9     ,  10.62    ,  28.32    ,
         8.5255  ,  11.618044,   9.317044,   9.317044,  98.126794,
        30.68    ,   9.317044,  12.409706,  12.39    ,   8.319   ,
        34.3675  ,  15.34    ,  35.4     ,  27.671   ,  35.4     ,
         9.145   ])

In [94]:
fare_with_tax=pd.Series(fare_with_tax)

In [96]:
df['fare_with_tax'] = fare_with_tax
df.head()

,survived,pclass,gender,age,sibsp,parch,fare,embarked,deck,fare_with_tax
0,0,3,male,22.0,1,0,7.2500,S,NaN,8.555000
1,1,1,female,38.0,1,0,71.2833,C,C,84.114294
2,1,3,female,26.0,0,0,7.9250,S,NaN,9.351500
3,1,1,female,35.0,1,0,53.1000,S,C,62.658000
4,0,3,male,35.0,0,0,8.0500,S,NaN,9.499000

18. create a numpy array from the fare column and :
     - replace all fares less than 10 with 10

In [97]:
fare_arr=np.array( df['fare']  )
fare_arr

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.05  ,
         8.05  ,   7.8542,  61.175 ,  20.575 ,   7.25  ,   8.05  ,
        34.6542,  63.3583,  23.    ,  26.    ,   7.8958,   7.8958,
        77.2875,   8.6542,   7.925 ,   7.8958,   7.65  ,   7.775 ,
         7.8958,  24.15  ,  52.    ,  14.4542,   8.05  ,   9.825 ,
        14.4583,   7.925 ,   7.75  ,  21.    , 247.5208,  31.275 ,
        73.5   ,   8.05  ,  30.0708,  13.    ,  77.2875,  11.2417,
         7.75  ,   7.1417,  22.3583,   6.975 ,   7.8958,   7.05  ,
        14.5   ,  26.    ,  13.    ,  15.0458,  26.2833,  53.1   ,
         9.2167,  79.2   ,  15.2458,   7.75  ,  15.85  ,   6.75  ,
        11.5   ,  36.75  ,   7.7958,  34.375 ,  26.    ,  13.    ,
        12.525 ,  66.6   ,   8.05  ,  14.5   ,   7.3125,  61.3792,
         7.7333,   8.05  ,   8.6625,  69.55  ,  16.1   ,  15.75  ,
         7.775 ,   8.6625,  39.6875,  20.525 ,  55.    ,  27.9   ,
        25.925 ,  56.4958,  33.5   ,  29.125 ,  11.1333,   7.925 ,
        30.6958,   7.8542,  25.4667,  28.7125,  13.    ,   0.    ,
        69.55  ,  15.05  ,  31.3875,  39.    ,  22.025 ,  50.    ,
        15.5   ,  26.55  ,  15.5   ,   7.8958,  13.    ,  13.    ,
         7.8542,  26.    ,  27.7208, 146.5208,   7.75  ,   8.4042,
         7.75  ,  13.    ,   9.5   ,  69.55  ,   6.4958,   7.225 ,
         8.05  ,  10.4625,  15.85  ,  18.7875,   7.75  ,  31.    ,
         7.05  ,  21.    ,   7.25  ,  13.    ,   7.75  , 113.275 ,
         7.925 ,  27.    ,  76.2917,  10.5   ,   8.05  ,  13.    ,
         8.05  ,   7.8958,  90.    ,   9.35  ,  10.5   ,   7.25  ,
        13.    ,  25.4667,  83.475 ,   7.775 ,  13.5   ,  31.3875,
        10.5   ,   7.55  ,  26.    ,  26.25  ,  10.5   ,  12.275 ,
        14.4542,  15.5   ,  10.5   ,   7.125 ,   7.225 ,  90.    ,
         7.775 ,  14.5   ,  52.5542,  26.    ,   7.25  ,  10.4625,
        26.55  ,  16.1   ,  20.2125,  15.2458,  79.2   ,  86.5   ,
       512.3292,  26.    ,   7.75  ,  31.3875,  79.65  ,   0.    ,
         7.75  ,  10.5   ,  39.6875,   7.775 , 153.4625, 135.6333,
        31.    ,   0.    ,  19.5   ,  29.7   ,   7.75  ,  77.9583,
         7.75  ,   0.    ,  29.125 ,  20.25  ,   7.75  ,   7.8542,
         9.5   ,   8.05  ,  26.    ,   8.6625,   9.5   ,   7.8958,
        13.    ,   7.75  ,  78.85  ,  91.0792,  12.875 ,   8.85  ,
         7.8958,  27.7208,   7.2292, 151.55  ,  30.5   , 247.5208,
         7.75  ,  23.25  ,   0.    ,  12.35  ,   8.05  , 151.55  ,
       110.8833, 108.9   ,  24.    ,  56.9292,  83.1583, 262.375 ,
        26.    ,   7.8958,  26.25  ,   7.8542,  26.    ,  14.    ,
       164.8667, 134.5   ,   7.25  ,   7.8958,  12.35  ,  29.    ,
        69.55  , 135.6333,   6.2375,  13.    ,  20.525 ,  57.9792,
        23.25  ,  28.5   , 153.4625,  18.    , 133.65  ,   7.8958,
        66.6   , 134.5   ,   8.05  ,  35.5   ,  26.    , 263.    ,
        13.    ,  13.    ,  13.    ,  13.    ,  13.    ,  16.1   ,
        15.9   ,   8.6625,   9.225 ,  35.    ,   7.2292,  17.8   ,
         7.225 ,   9.5   ,  55.    ,  13.    ,   7.8792,   7.8792,
        27.9   ,  27.7208,  14.4542,   7.05  ,  15.5   ,   7.25  ,
        75.25  ,   7.2292,   7.75  ,  69.3   ,  55.4417,   6.4958,
         8.05  , 135.6333,  21.075 ,  82.1708,   7.25  , 211.5   ,
         4.0125,   7.775 , 227.525 ,  15.7417,   7.925 ,  52.    ,
         7.8958,  73.5   ,  46.9   ,  13.    ,   7.7292,  12.    ,
       120.    ,   7.7958,   7.925 , 113.275 ,  16.7   ,   7.7958,
         7.8542,  26.    ,  10.5   ,  12.65  ,   7.925 ,   8.05  ,
         9.825 ,  15.85  ,   8.6625,  21.    ,   7.75  ,  18.75  ,
         7.775 ,  25.4667,   7.8958,   6.8583,  90.    ,   0.    ,
         7.925 ,   8.05  ,  32.5   ,  13.    ,  13.    ,  24.15  ,
         7.8958,   7.7333,   7.875 ,  14.4   ,  20.2125,   7.25  ,
        26.    ,  26.    ,   7.75  ,   8.05  ,  26.55  ,  16.1   ,
        26.    ,   7.125 ,  55.9   , 120.    ,  34.375 ,  18.75  ,
       263.    ,  10.5   ,  26.25  ,   9.5   ,   7.775 ,  13.    ,
         8.1125,  81.8583,  19.5   ,  26.55  ,  19.2583,  30.5   ,
        27.75  ,  19.9667,  27.75  ,  89.1042,   8.05  ,   7.8958,
        26.55  ,  51.8625,  10.5   ,   7.75  ,  26.55  ,   8.05  ,
        38.5   ,  13.    ,   8.05  ,   7.05  ,   0.    ,  26.55  ,
         7.725 ,  19.2583,   7.25  ,   8.6625,  27.75  ,  13.7917,
         9.8375,  52.    ,  21.    ,   7.0458,   7.5208,  12.2875,
        46.9   ,   0.    ,   8.05  ,   9.5875,  91.0792,  25.4667,
        90.    ,  29.7   ,   8.05  ,  15.9   ,  19.9667,   7.25  ,
        30.5   ,  49.5042,   8.05  ,  14.4583,  78.2667,  15.1   ,
       151.55  ,   7.7958,   8.6625,   7.75  ,   7.6292,   9.5875,
        86.5   , 108.9   ,  26.    ,  26.55  ,  22.525 ,  56.4958,
         7.75  ,   8.05  ,  26.2875,  59.4   ,   7.4958,  34.0208,
        10.5   ,  24.15  ,  26.    ,   7.8958,  93.5   ,   7.8958,
         7.225 ,  57.9792,   7.2292,   7.75  ,  10.5   , 221.7792,
         7.925 ,  11.5   ,  26.    ,   7.2292,   7.2292,  22.3583,
         8.6625,  26.25  ,  26.55  , 106.425 ,  14.5   ,  49.5   ,
        71.    ,  31.275 ,  31.275 ,  26.    , 106.425 ,  26.    ,
        26.    ,  13.8625,  20.525 ,  36.75  , 110.8833,  26.    ,
         7.8292,   7.225 ,   7.775 ,  26.55  ,  39.6   , 227.525 ,
        79.65  ,  17.4   ,   7.75  ,   7.8958,  13.5   ,   8.05  ,
         8.05  ,  24.15  ,   7.8958,  21.075 ,   7.2292,   7.8542,
        10.5   ,  51.4792,  26.3875,   7.75  ,   8.05  ,  14.5   ,
        13.    ,  55.9   ,  14.4583,   7.925 ,  30.    , 110.8833,
        26.    ,  40.125 ,   8.7125,  79.65  ,  15.    ,  79.2   ,
         8.05  ,   8.05  ,   7.125 ,  78.2667,   7.25  ,   7.75  ,
        26.    ,  24.15  ,  33.    ,   0.    ,   7.225 ,  56.9292,
        27.    ,   7.8958,  42.4   ,   8.05  ,  26.55  ,  15.55  ,
         7.8958,  30.5   ,  41.5792, 153.4625,  31.275 ,   7.05  ,
        15.5   ,   7.75  ,   8.05  ,  65.    ,  14.4   ,  16.1   ,
        39.    ,  10.5   ,  14.4542,  52.5542,  15.7417,   7.8542,
        16.1   ,  32.3208,  12.35  ,  77.9583,   7.8958,   7.7333,
        30.    ,   7.0542,  30.5   ,   0.    ,  27.9   ,  13.    ,
         7.925 ,  26.25  ,  39.6875,  16.1   ,   7.8542,  69.3   ,
        27.9   ,  56.4958,  19.2583,  76.7292,   7.8958,  35.5   ,
         7.55  ,   7.55  ,   7.8958,  23.    ,   8.4333,   7.8292,
         6.75  ,  73.5   ,   7.8958,  15.5   ,  13.    , 113.275 ,
       133.65  ,   7.225 ,  25.5875,   7.4958,   7.925 ,  73.5   ,
        13.    ,   7.775 ,   8.05  ,  52.    ,  39.    ,  52.    ,
        10.5   ,  13.    ,   0.    ,   7.775 ,   8.05  ,   9.8417,
        46.9   , 512.3292,   8.1375,  76.7292,   9.225 ,  46.9   ,
        39.    ,  41.5792,  39.6875,  10.1708,   7.7958, 211.3375,
        57.    ,  13.4167,  56.4958,   7.225 ,  26.55  ,  13.5   ,
         8.05  ,   7.7333, 110.8833,   7.65  , 227.525 ,  26.2875,
        14.4542,   7.7417,   7.8542,  26.    ,  13.5   ,  26.2875,
       151.55  ,  15.2458,  49.5042,  26.55  ,  52.    ,   9.4833,
        13.    ,   7.65  , 227.525 ,  10.5   ,  15.5   ,   7.775 ,
        33.    ,   7.0542,  13.    ,  13.    ,  53.1   ,   8.6625,
        21.    ,   7.7375,  26.    ,   7.925 , 211.3375,  18.7875,
         0.    ,  13.    ,  13.    ,  16.1   ,  34.375 , 512.3292,
         7.8958,   7.8958,  30.    ,  78.85  , 262.375 ,  16.1   ,
         7.925 ,  71.    ,  20.25  ,  13.    ,  53.1   ,   7.75  ,
        23.    ,  12.475 ,   9.5   ,   7.8958,  65.    ,  14.5   ,
         7.7958,  11.5   ,   8.05  ,  86.5   ,  14.5   ,   7.125 ,
         7.2292, 120.    ,   7.775 ,  77.9583,  39.6   ,   7.75  ,
        24.15  ,   8.3625,   9.5   ,   7.8542,  10.5   ,   7.225 ,
        23.    ,   7.75  ,   7.75  ,  12.475 ,   7.7375, 211.3375,
         7.2292,  57.    ,  30.    ,  23.45  ,   7.05  ,   7.25  ,
         7.4958,  29.125 ,  20.575 ,  79.2   ,   7.75  ,  26.    ,
        69.55  ,  30.6958,   7.8958,  13.    ,  25.9292,   8.6833,
         7.2292,  24.15  ,  13.    ,  26.25  , 120.    ,   8.5167,
         6.975 ,   7.775 ,   0.    ,   7.775 ,  13.    ,  53.1   ,
         7.8875,  24.15  ,  10.5   ,  31.275 ,   8.05  ,   0.    ,
         7.925 ,  37.0042,   6.45  ,  27.9   ,  93.5   ,   8.6625,
         0.    ,  12.475 ,  39.6875,   6.95  ,  56.4958,  37.0042,
         7.75  ,  80.    ,  14.4542,  18.75  ,   7.2292,   7.8542,
         8.3   ,  83.1583,   8.6625,   8.05  ,  56.4958,  29.7   ,
         7.925 ,  10.5   ,  31.    ,   6.4375,   8.6625,   7.55  ,
        69.55  ,   7.8958,  33.    ,  89.1042,  31.275 ,   7.775 ,
        15.2458,  39.4   ,  26.    ,   9.35  , 164.8667,  26.55  ,
        19.2583,   7.2292,  14.1083,  11.5   ,  25.9292,  69.55  ,
        13.    ,  13.    ,  13.8583,  50.4958,   9.5   ,  11.1333,
         7.8958,  52.5542,   5.    ,   9.    ,  24.    ,   7.225 ,
         9.8458,   7.8958,   7.8958,  83.1583,  26.    ,   7.8958,
        10.5167,  10.5   ,   7.05  ,  29.125 ,  13.    ,  30.    ,
        23.45  ,  30.    ,   7.75  ])

In [98]:
fare_arr[fare_arr < 10] = 10
fare_arr

array([ 10.    ,  71.2833,  10.    ,  53.1   ,  10.    ,  10.    ,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        10.    ,  31.275 ,  10.    ,  16.    ,  29.125 ,  13.    ,
        18.    ,  10.    ,  26.    ,  13.    ,  10.    ,  35.5   ,
        21.075 ,  31.3875,  10.    , 263.    ,  10.    ,  10.    ,
        27.7208, 146.5208,  10.    ,  10.5   ,  82.1708,  52.    ,
        10.    ,  10.    ,  18.    ,  11.2417,  10.    ,  21.    ,
        10.    ,  41.5792,  10.    ,  10.    ,  15.5   ,  10.    ,
        21.6792,  17.8   ,  39.6875,  10.    ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,  10.    ,  27.75  ,  46.9   ,
        10.    ,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,  10.    ,  10.    ,  10.    ,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,  10.    ,  10.    ,  10.    ,
        29.    ,  12.475 ,  10.    ,  10.    ,  10.    ,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,  10.    , 263.    ,  10.    ,
        10.    ,  10.    ,  61.175 ,  20.575 ,  10.    ,  10.    ,
        34.6542,  63.3583,  23.    ,  26.    ,  10.    ,  10.    ,
        77.2875,  10.    ,  10.    ,  10.    ,  10.    ,  10.    ,
        10.    ,  24.15  ,  52.    ,  14.4542,  10.    ,  10.    ,
        14.4583,  10.    ,  10.    ,  21.    , 247.5208,  31.275 ,
        73.5   ,  10.    ,  30.0708,  13.    ,  77.2875,  11.2417,
        10.    ,  10.    ,  22.3583,  10.    ,  10.    ,  10.    ,
        14.5   ,  26.    ,  13.    ,  15.0458,  26.2833,  53.1   ,
        10.    ,  79.2   ,  15.2458,  10.    ,  15.85  ,  10.    ,
        11.5   ,  36.75  ,  10.    ,  34.375 ,  26.    ,  13.    ,
        12.525 ,  66.6   ,  10.    ,  14.5   ,  10.    ,  61.3792,
        10.    ,  10.    ,  10.    ,  69.55  ,  16.1   ,  15.75  ,
        10.    ,  10.    ,  39.6875,  20.525 ,  55.    ,  27.9   ,
        25.925 ,  56.4958,  33.5   ,  29.125 ,  11.1333,  10.    ,
        30.6958,  10.    ,  25.4667,  28.7125,  13.    ,  10.    ,
        69.55  ,  15.05  ,  31.3875,  39.    ,  22.025 ,  50.    ,
        15.5   ,  26.55  ,  15.5   ,  10.    ,  13.    ,  13.    ,
        10.    ,  26.    ,  27.7208, 146.5208,  10.    ,  10.    ,
        10.    ,  13.    ,  10.    ,  69.55  ,  10.    ,  10.    ,
        10.    ,  10.4625,  15.85  ,  18.7875,  10.    ,  31.    ,
        10.    ,  21.    ,  10.    ,  13.    ,  10.    , 113.275 ,
        10.    ,  27.    ,  76.2917,  10.5   ,  10.    ,  13.    ,
        10.    ,  10.    ,  90.    ,  10.    ,  10.5   ,  10.    ,
        13.    ,  25.4667,  83.475 ,  10.    ,  13.5   ,  31.3875,
        10.5   ,  10.    ,  26.    ,  26.25  ,  10.5   ,  12.275 ,
        14.4542,  15.5   ,  10.5   ,  10.    ,  10.    ,  90.    ,
        10.    ,  14.5   ,  52.5542,  26.    ,  10.    ,  10.4625,
        26.55  ,  16.1   ,  20.2125,  15.2458,  79.2   ,  86.5   ,
       512.3292,  26.    ,  10.    ,  31.3875,  79.65  ,  10.    ,
        10.    ,  10.5   ,  39.6875,  10.    , 153.4625, 135.6333,
        31.    ,  10.    ,  19.5   ,  29.7   ,  10.    ,  77.9583,
        10.    ,  10.    ,  29.125 ,  20.25  ,  10.    ,  10.    ,
        10.    ,  10.    ,  26.    ,  10.    ,  10.    ,  10.    ,
        13.    ,  10.    ,  78.85  ,  91.0792,  12.875 ,  10.    ,
        10.    ,  27.7208,  10.    , 151.55  ,  30.5   , 247.5208,
        10.    ,  23.25  ,  10.    ,  12.35  ,  10.    , 151.55  ,
       110.8833, 108.9   ,  24.    ,  56.9292,  83.1583, 262.375 ,
        26.    ,  10.    ,  26.25  ,  10.    ,  26.    ,  14.    ,
       164.8667, 134.5   ,  10.    ,  10.    ,  12.35  ,  29.    ,
        69.55  , 135.6333,  10.    ,  13.    ,  20.525 ,  57.9792,
        23.25  ,  28.5   , 153.4625,  18.    , 133.65  ,  10.    ,
        66.6   , 134.5   ,  10.    ,  35.5   ,  26.    , 263.    ,
        13.    ,  13.    ,  13.    ,  13.    ,  13.    ,  16.1   ,
        15.9   ,  10.    ,  10.    ,  35.    ,  10.    ,  17.8   ,
        10.    ,  10.    ,  55.    ,  13.    ,  10.    ,  10.    ,
        27.9   ,  27.7208,  14.4542,  10.    ,  15.5   ,  10.    ,
        75.25  ,  10.    ,  10.    ,  69.3   ,  55.4417,  10.    ,
        10.    , 135.6333,  21.075 ,  82.1708,  10.    , 211.5   ,
        10.    ,  10.    , 227.525 ,  15.7417,  10.    ,  52.    ,
        10.    ,  73.5   ,  46.9   ,  13.    ,  10.    ,  12.    ,
       120.    ,  10.    ,  10.    , 113.275 ,  16.7   ,  10.    ,
        10.    ,  26.    ,  10.5   ,  12.65  ,  10.    ,  10.    ,
        10.    ,  15.85  ,  10.    ,  21.    ,  10.    ,  18.75  ,
        10.    ,  25.4667,  10.    ,  10.    ,  90.    ,  10.    ,
        10.    ,  10.    ,  32.5   ,  13.    ,  13.    ,  24.15  ,
        10.    ,  10.    ,  10.    ,  14.4   ,  20.2125,  10.    ,
        26.    ,  26.    ,  10.    ,  10.    ,  26.55  ,  16.1   ,
        26.    ,  10.    ,  55.9   , 120.    ,  34.375 ,  18.75  ,
       263.    ,  10.5   ,  26.25  ,  10.    ,  10.    ,  13.    ,
        10.    ,  81.8583,  19.5   ,  26.55  ,  19.2583,  30.5   ,
        27.75  ,  19.9667,  27.75  ,  89.1042,  10.    ,  10.    ,
        26.55  ,  51.8625,  10.5   ,  10.    ,  26.55  ,  10.    ,
        38.5   ,  13.    ,  10.    ,  10.    ,  10.    ,  26.55  ,
        10.    ,  19.2583,  10.    ,  10.    ,  27.75  ,  13.7917,
        10.    ,  52.    ,  21.    ,  10.    ,  10.    ,  12.2875,
        46.9   ,  10.    ,  10.    ,  10.    ,  91.0792,  25.4667,
        90.    ,  29.7   ,  10.    ,  15.9   ,  19.9667,  10.    ,
        30.5   ,  49.5042,  10.    ,  14.4583,  78.2667,  15.1   ,
       151.55  ,  10.    ,  10.    ,  10.    ,  10.    ,  10.    ,
        86.5   , 108.9   ,  26.    ,  26.55  ,  22.525 ,  56.4958,
        10.    ,  10.    ,  26.2875,  59.4   ,  10.    ,  34.0208,
        10.5   ,  24.15  ,  26.    ,  10.    ,  93.5   ,  10.    ,
        10.    ,  57.9792,  10.    ,  10.    ,  10.5   , 221.7792,
        10.    ,  11.5   ,  26.    ,  10.    ,  10.    ,  22.3583,
        10.    ,  26.25  ,  26.55  , 106.425 ,  14.5   ,  49.5   ,
        71.    ,  31.275 ,  31.275 ,  26.    , 106.425 ,  26.    ,
        26.    ,  13.8625,  20.525 ,  36.75  , 110.8833,  26.    ,
        10.    ,  10.    ,  10.    ,  26.55  ,  39.6   , 227.525 ,
        79.65  ,  17.4   ,  10.    ,  10.    ,  13.5   ,  10.    ,
        10.    ,  24.15  ,  10.    ,  21.075 ,  10.    ,  10.    ,
        10.5   ,  51.4792,  26.3875,  10.    ,  10.    ,  14.5   ,
        13.    ,  55.9   ,  14.4583,  10.    ,  30.    , 110.8833,
        26.    ,  40.125 ,  10.    ,  79.65  ,  15.    ,  79.2   ,
        10.    ,  10.    ,  10.    ,  78.2667,  10.    ,  10.    ,
        26.    ,  24.15  ,  33.    ,  10.    ,  10.    ,  56.9292,
        27.    ,  10.    ,  42.4   ,  10.    ,  26.55  ,  15.55  ,
        10.    ,  30.5   ,  41.5792, 153.4625,  31.275 ,  10.    ,
        15.5   ,  10.    ,  10.    ,  65.    ,  14.4   ,  16.1   ,
        39.    ,  10.5   ,  14.4542,  52.5542,  15.7417,  10.    ,
        16.1   ,  32.3208,  12.35  ,  77.9583,  10.    ,  10.    ,
        30.    ,  10.    ,  30.5   ,  10.    ,  27.9   ,  13.    ,
        10.    ,  26.25  ,  39.6875,  16.1   ,  10.    ,  69.3   ,
        27.9   ,  56.4958,  19.2583,  76.7292,  10.    ,  35.5   ,
        10.    ,  10.    ,  10.    ,  23.    ,  10.    ,  10.    ,
        10.    ,  73.5   ,  10.    ,  15.5   ,  13.    , 113.275 ,
       133.65  ,  10.    ,  25.5875,  10.    ,  10.    ,  73.5   ,
        13.    ,  10.    ,  10.    ,  52.    ,  39.    ,  52.    ,
        10.5   ,  13.    ,  10.    ,  10.    ,  10.    ,  10.    ,
        46.9   , 512.3292,  10.    ,  76.7292,  10.    ,  46.9   ,
        39.    ,  41.5792,  39.6875,  10.1708,  10.    , 211.3375,
        57.    ,  13.4167,  56.4958,  10.    ,  26.55  ,  13.5   ,
        10.    ,  10.    , 110.8833,  10.    , 227.525 ,  26.2875,
        14.4542,  10.    ,  10.    ,  26.    ,  13.5   ,  26.2875,
       151.55  ,  15.2458,  49.5042,  26.55  ,  52.    ,  10.    ,
        13.    ,  10.    , 227.525 ,  10.5   ,  15.5   ,  10.    ,
        33.    ,  10.    ,  13.    ,  13.    ,  53.1   ,  10.    ,
        21.    ,  10.    ,  26.    ,  10.    , 211.3375,  18.7875,
        10.    ,  13.    ,  13.    ,  16.1   ,  34.375 , 512.3292,
        10.    ,  10.    ,  30.    ,  78.85  , 262.375 ,  16.1   ,
        10.    ,  71.    ,  20.25  ,  13.    ,  53.1   ,  10.    ,
        23.    ,  12.475 ,  10.    ,  10.    ,  65.    ,  14.5   ,
        10.    ,  11.5   ,  10.    ,  86.5   ,  14.5   ,  10.    ,
        10.    , 120.    ,  10.    ,  77.9583,  39.6   ,  10.    ,
        24.15  ,  10.    ,  10.    ,  10.    ,  10.5   ,  10.    ,
        23.    ,  10.    ,  10.    ,  12.475 ,  10.    , 211.3375,
        10.    ,  57.    ,  30.    ,  23.45  ,  10.    ,  10.    ,
        10.    ,  29.125 ,  20.575 ,  79.2   ,  10.    ,  26.    ,
        69.55  ,  30.6958,  10.    ,  13.    ,  25.9292,  10.    ,
        10.    ,  24.15  ,  13.    ,  26.25  , 120.    ,  10.    ,
        10.    ,  10.    ,  10.    ,  10.    ,  13.    ,  53.1   ,
        10.    ,  24.15  ,  10.5   ,  31.275 ,  10.    ,  10.    ,
        10.    ,  37.0042,  10.    ,  27.9   ,  93.5   ,  10.    ,
        10.    ,  12.475 ,  39.6875,  10.    ,  56.4958,  37.0042,
        10.    ,  80.    ,  14.4542,  18.75  ,  10.    ,  10.    ,
        10.    ,  83.1583,  10.    ,  10.    ,  56.4958,  29.7   ,
        10.    ,  10.5   ,  31.    ,  10.    ,  10.    ,  10.    ,
        69.55  ,  10.    ,  33.    ,  89.1042,  31.275 ,  10.    ,
        15.2458,  39.4   ,  26.    ,  10.    , 164.8667,  26.55  ,
        19.2583,  10.    ,  14.1083,  11.5   ,  25.9292,  69.55  ,
        13.    ,  13.    ,  13.8583,  50.4958,  10.    ,  11.1333,
        10.    ,  52.5542,  10.    ,  10.    ,  24.    ,  10.    ,
        10.    ,  10.    ,  10.    ,  83.1583,  26.    ,  10.    ,
        10.5167,  10.5   ,  10.    ,  29.125 ,  13.    ,  30.    ,
        23.45  ,  30.    ,  10.    ])

19. create a new column called Age_Group:
    - Child : age<18
    - Adult :  10 to 60
    - Senior : age>60
      Then count passengers in each category

In [100]:
conditions=[
    df['age'] < 18,
    ( df['age'] >= 18) &  (df['age'] <= 60),
     df['age'] > 60
]
categories= ["Child","Adult","Senior"]
df["Age_Group"] = np.select (conditions,categories, default="Unknown")
print(df['Age_Group'].value_counts())

Age_Group
Adult      579
Unknown    177
Child      113
Senior      22
Name: count, dtype: int64

20. Find survival percentage for each passengers class

In [106]:
survival_per=df.groupby('pclass')['survived'].mean()*100
print(survival_per)

pclass
1    62.962963
2    47.282609
3    24.236253
Name: survived, dtype: float64

In [113]:
# formatting it
res = survival_per.reset_index()
res.columns=['Passenger Class','Survival Percentage']
print(res)

   Passenger Class  Survival Percentage
0                1            62.962963
1                2            47.282609
2                3            24.236253